# Generated by Django 4.1.7 on 2023-03-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_alter_post_author'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
